build_script:
 - appveyor-prebuild.bat
 - nuget restore ikvm9.sln
 - build.bat
 - 7z a -mm=Deflate -mmt=on -mx=9 ikvm-test-build.zip .\bin .\lib
test_script:
 - appveyor DownloadFile https://altushost-swe.dl.sourceforge.net/project/dacapobench/9.12-bach-MR1/dacapo-9.12-MR1-bach.jar
 - ikvmtest.bat avrora
 - ikvmtest.bat batik
 - ikvmtest.bat eclipse
 - ikvmtest.bat fop
 - ikvmtest.bat h2
 - ikvmtest.bat jython
 - ikvmtest.bat luindex
 - ikvmtest.bat lusearch
 - ikvmtest.bat lusearch-fix
 - ikvmtest.bat pmd
 - ikvmtest.bat sunflow
 - ikvmtest.bat tomcat
 - ikvmtest.bat tradebeans
 - ikvmtest.bat tradesoap
 - ikvmtest.bat xalan
artifacts:
 - path: ikvm-test-build.zip
   name: ikvm-test-build
   type: zip